#!/usr/bin/env python3
"""Clean up instrument .md files:
1. Delete non-instrument entries
2. Fix Simplified → Traditional Chinese titles
3. Fix mixed-language titles
4. Add Chinese translations for English-only titles
5. Merge duplicate instruments
"""
import sys
from pathlib import Path

CONTENT_DIR = Path(__file__).resolve().parent.parent / "content" / "instruments"

# ── 1. 非樂器條目（直接刪除）──────────────────────────────────────
NON_INSTRUMENT_SLUGS = {
    # 國家/地理
    "china", "germany", "indonesia", "russia", "united-states",
    "karelia", "vosges-mountains", "eastern-europe",
    # Wikipedia 系統頁
    "main-page",
    # 音樂風格/流派（非樂器）
    "bluegrass", "drone-music", "film-scoring", "game-music",
    "electroacoustic-music", "world-music-fusion",
    # 物理/理論概念
    "vibration", "string-vibration", "string-harmonic", "string-music",
    "reentrant-tuning", "scale-length-string-instruments",
    "tuning-mechanisms-for-stringed-instruments",
    # 樂器零件/分類概念
    "double-reed", "free-reed-aerophone", "free-reed-instrument",
    "edge-blown-aerophones", "reed-aerophones", "flue-pipe",
    "fret", "fingerboard", "hornbostelsachs-system",
    "bowed-instrument", "blown-idiophone", "struck-idiophone",
    "friction-idiophone", "single-reed-instrument",
    "directly-struck-membranophones", "lamellophone",
    "course-music", "didgeridoo-as-lip-reed-relation",
    "harp-glissando-scoring",
    # 器材/設備
    "instrument-amplifier", "contact-microphone",
    "sample-libraries", "sampler-library", "daw-instruments",
    # 動作/技巧（非樂器）
    "tap-dance", "clapping", "finger-snaps", "whipcracking",
    "flamenco-palmas", "body-percussion", "fanfare",
    # 合奏編制（非單一樂器）
    "brass-band", "marching-band", "jazz-combo", "string-quartet",
    "orchestra", "rock-band", "samba-school", "wind-band",
    "percussion-ensemble", "carnatic-ensemble", "choro-ensemble",
    "dhrupad-ensemble", "taiko-ensemble", "tamburica-orchestra",
    "tango-ensemble", "okinawan-ensemble", "korean-court-music",
    "japanese-gagaku", "hybrid-orchestra", "rondalla",
    "mariachi", "chinese-orchestra", "griot-ensemble",
    "andean-ensemble", "balinese-gamelan", "javanese-gamelan",
    "pinpeat", "piphat", "mariachi-brass",
}

# ── 2. 標題簡體→繁體字符對照 ────────────────────────────────────────
S2T_TITLE = {
    "手风琴": "手風琴",
    "六角手风琴": "六角手風琴",
    "班东尼琴": "班東尼琴",
    "钢琴": "鋼琴",
    "管风琴": "管風琴",
    "英国管": "英國管",
    "爱尔兰风笛": "愛爾蘭風笛",
    "热瓦甫": "熱瓦甫",
    "东欧": "東歐",
    "直击式膜鸣乐器": "直擊式膜鳴樂器",
    "棘轮 (乐器)": "棘輪（樂器）",
    "摇铃 (打击乐器)": "搖鈴（打擊樂器）",
    "哨子 (乐器)": "哨子（樂器）",
    "中华人民共和国": "中華人民共和國",
    "德国": "德國",
    "印度尼西亚": "印度尼西亞",
    "俄罗斯": "俄羅斯",
    "电吉他": "電吉他",
    "民谣吉他": "民謠吉他",
    "俄罗斯吉他": "俄羅斯吉他",
    "锡塔琴": "錫塔琴",
    "颤音琴": "顫音琴",
}

# ── 3. 混雜英中標題修正 ──────────────────────────────────────────────
MIXED_TITLE_FIX = {
    "Electric-原聲吉他": "電插原聲吉他",
    "Semi-原聲吉他": "半空心吉他",
    "Electric 琵琶": "電琵琶",
    "小提琴 family": "提琴族",
    "Mando大提琴": "曼陀大提琴",
    "Mando魯特琴": "曼陀魯特琴",
    "馬林巴琴phone": "馬林巴手機琴",
    "豎琴ejji": "豎琴吉他",
    "吉他 battente": "巴坦特吉他",
    "吉他rón mexicano": "墨西哥大吉他",
    "Yoke 魯特琴s": "軛型魯特琴",
    "Bass Guitar": "貝斯吉他",
    "Lyre Guitar": "里拉吉他",
    "Baritone 雙簧管": "中低音雙簧管",
    "Piccolo 雙簧管": "高音雙簧管",
    "雙簧管 da caccia": "狩獵雙簧管",
    "雙簧管 d'amore": "愛之雙簧管",
    "Baritone sarrusophone（暫譯）": "中低音薩魯梭風",
    "Alto sarrusophone（暫譯）": "中音薩魯梭風",
    "Bass sarrusophone（暫譯）": "低音薩魯梭風",
    "Soprano sarrusophone（暫譯）": "高音薩魯梭風",
    "Tenor sarrusophone（暫譯）": "次中音薩魯梭風",
    "Contrabass sarrusophone（暫譯）": "倍低音薩魯梭風",
    "Chromatic 小號": "半音小號",
    "Cross-strung 豎琴": "交叉弦豎琴",
    "Inline chromatic 豎琴": "直列半音豎琴",
    "Lever 豎琴": "拉桿豎琴",
    "Pedal 豎琴": "踏板豎琴",
    "Concert 豎琴": "音樂廳豎琴",
    "Celtic 豎琴": "凱爾特豎琴",
    "Space 豎琴": "太空豎琴",
    "Earth 豎琴": "大地豎琴",
    "Electric 豎琴": "電豎琴",
    "Glass 豎琴": "玻璃豎琴",
    "Harp 吉他": "豎琴吉他",
    "Welsh Triple 豎琴": "威爾斯三排豎琴",
    "Concert Harp": "音樂廳豎琴",
    "Barrel 鼓": "桶鼓",
    "Conical 鼓": "錐形鼓",
    "Cylindrical 鼓": "圓柱鼓",
    "Frame 鼓": "框架鼓",
    "Friction 鼓": "摩擦鼓",
    "Hourglass 鼓": "沙漏鼓",
    "Kettle 鼓": "鍋鼓",
    "Log Drum": "木槽鼓",
    "Ocean Drum": "海浪鼓",
    "Pellet 鼓": "圓珠鼓",
    "Rain Drum": "雨鼓",
    "Rattle 鼓": "搖鼓",
    "Slit 鼓": "裂縫鼓",
    "Steel 鼓": "鋼鼓",
    "Tank 鼓": "鋼舌鼓",
    "Tom-tom 鼓": "通通鼓",
    "Tubular 鼓": "管狀鼓",
    "Hi-hat 鈸": "踩鈸",
    "Clash 鈸s": "對鈸",
    "Splash 鈸": "濺鈸",
    "Suspended Cymbal": "懸吊鈸",
    "Sleigh 鐘": "鈴鐺",
    "Tubular 鐘": "管鐘",
    "Cow鐘 (instrument)": "牛鈴",
    "鐘 (instrument)": "鈴鐺",
    "鐘 tree": "樹鈴",
    "Geng鑼": "根貢",
    "Slit 鑼": "裂縫鑼",
    "Crum號角": "彎管號",
    "English 號角": "英國管",
    "Martins號角": "號角",
    "Party 號角": "派對號角",
    "Surma-號角": "蘇爾瑪號",
    "號角bostel–Sachs system": "霍恩博斯特爾–薩克斯分類法",
    "Glass 馬林巴琴": "玻璃馬林巴琴",
    "Kaffir 鋼琴": "南非鐵片琴",
    "Thumb 鋼琴": "拇指鋼琴",
    "Toy 鋼琴": "玩具鋼琴",
    "長笛s with duct": "有導管長笛",
    "Eunuch 長笛": "噶噶笛",
    "Piston 長笛": "活塞長笛",
    "Willow 長笛": "柳木長笛",
    "Western Flute": "西洋長笛",
    "Portuguese 吉他": "葡萄牙吉他",
    "Extended-range classical 吉他": "擴展音域古典吉他",
    "Ten-string 吉他": "十弦吉他",
    "Tenor 吉他": "次中音吉他",
    "Twelve-string 吉他": "十二弦吉他",
    "Likembe la basse": "低音利肯貝",
    "Hydrodaktulopsychic口琴": "水鍵口琴",
    "Samhulori / Samulnori": "四物農樂",
    "鈴鼓 de Bearn": "貝亞恩手鼓",
    "Tambura bugarija": "布加利亞坦布拉琴",
    "C調薩克斯風": "C調薩克斯風",
    "箏 (musical instrument)": "箏",
    "Roland TB-303": "羅蘭 TB-303",
    "Roland TR-808": "羅蘭 TR-808",
}

# ── 4. English original_name → 繁體中文 title ────────────────────────
EN_TO_ZH = {
    # 西方管樂
    "Clarinet": "單簧管",
    "Oboe": "雙簧管",
    "Bassoon": "低音管",
    "Flute": "長笛",
    "Piccolo": "短笛",
    "Saxophone": "薩克斯風",
    "Trumpet": "小號",
    "Trombone": "長號",
    "Tuba": "大號",
    "French horn": "法國號",
    "Euphonium": "上低音號",
    "Flugelhorn": "翼號",
    "Cornet": "短號",
    "Mellophone": "次中音號",
    "Sousaphone": "低音大號",
    "Saxhorn": "薩克斯號",
    "Ophicleide": "奧菲克萊德號",
    "Sackbut": "薩克布特長號",
    "Serpent": "蛇形管號",
    "Buccina": "布奇那號",
    "Cornu": "科爾奴號",
    "Carnyx": "卡爾尼克斯號",
    "Didgeridoo": "迪吉里杜管",
    "Bugle": "軍號",
    "Keyed bugle": "按鍵號",
    "Shofar": "羊角號",
    "Conch": "海螺號",
    "Olifant": "象牙號",
    "Lur": "盧爾號",
    "Bucium": "布奇烏姆號",
    "Trembita": "特倫比塔號",
    "Dungchen": "藏傳長號",
    "Kangling": "脛骨號",
    # 西方弦樂
    "Violin": "小提琴",
    "Viola": "中提琴",
    "Cello": "大提琴",
    "Double bass": "低音提琴",
    "Viol": "古提琴",
    "Viola da gamba": "低音古提琴",
    "Violino piccolo": "小型小提琴",
    "Hardanger fiddle": "哈丹格爾小提琴",
    "Stroh violin": "斯特羅小提琴",
    "Electric violin": "電小提琴",
    "Fiddle": "民俗小提琴",
    "Nail violin": "釘板小提琴",
    "Wheel fiddle": "輪擦小提琴",
    "Rebec": "雷貝克琴",
    "Crwth": "克魯斯琴",
    "Vielle": "中世紀維埃爾琴",
    "Nyckelharpa": "鍵鈕弓琴",
    "Hurdy-gurdy": "輪擦提琴",
    "Gudok": "古多克琴",
    "Jouhikko": "約伊希科琴",
    "Gusle": "古斯勒琴",
    "Lijerica": "利耶里卡琴",
    "Gadulka": "加杜爾卡琴",
    "Igil": "伊吉勒琴",
    "Morin khuur": "馬頭琴",
    "Kamaycha": "卡馬伊恰琴",
    "Ghijak": "吉賈克琴",
    "Rebab": "熱巴普",
    "Sarangi": "薩朗吉琴",
    "Esraj": "以斯拉吉琴",
    "Dilruba": "迪爾魯巴琴",
    "Surbahar": "蘇爾巴哈琴",
    "Haegeum": "奚琴",
    "Haegum": "奚琴",
    "Kokyu": "胡弓",
    "Tagelharpa": "塔格爾哈帕琴",
    "Talharpa": "塔爾哈帕琴",
    "Pochette": "袋形小提琴",
    "Lira da braccio": "臂提里拉琴",
    "Lira calabrese": "卡拉布里亞里拉琴",
    "Tromba marina": "海洋小號弦琴",
    "Waterphone": "水音琴",
    # 吉他族
    "Guitar": "吉他",
    "Acoustic guitar": "原聲吉他",
    "Classical guitar": "古典吉他",
    "Electric guitar": "電吉他",
    "Steel-string acoustic guitar": "鋼弦原聲吉他",
    "Bass guitar": "貝斯吉他",
    "Acoustic bass guitar": "原聲貝斯吉他",
    "Archtop guitar": "拱頂吉他",
    "Baroque guitar": "巴洛克吉他",
    "Flamenco guitar": "佛朗明哥吉他",
    "Dobro": "多布羅滑棒吉他",
    "Resonator guitar": "共鳴器吉他",
    "Eight-string guitar": "八弦吉他",
    "Twelve-string guitar": "十二弦吉他",
    "Ten-string guitar": "十弦吉他",
    "Tenor guitar": "次中音吉他",
    "Portuguese guitar": "葡萄牙吉他",
    "Russian guitar": "俄羅斯七弦吉他",
    "Harp guitar": "豎琴吉他",
    "Lyre guitar": "里拉吉他",
    "Guitar battente": "巴坦特吉他",
    "Guitarrón mexicano": "墨西哥大吉他",
    "Extended-range classical guitar": "擴展音域古典吉他",
    "Electric-acoustic guitar": "電插原聲吉他",
    "Semi-acoustic guitar": "半空心電吉他",
    "Lap steel guitar": "鋼棒滑音吉他",
    "Chitarra italiana": "義大利吉他",
    "Timple": "加那利小吉他",
    # 魯特族
    "Lute": "魯特琴",
    "Archlute": "拱形魯特琴",
    "Theorbo": "泰奧博琴",
    "Mandolin": "曼陀鈴",
    "Mandocello": "曼陀大提琴",
    "Banjo": "班卓琴",
    "Ukulele": "烏克麗麗",
    "Balalaika": "巴拉萊卡琴",
    "Domra": "多姆拉琴",
    "Cittern": "希特恩琴",
    "Bandurria": "班杜里亞琴",
    "Tiple": "蒂普勒琴",
    "Charango": "恰朗戈琴",
    "Cuatro": "夸特羅琴",
    "Cuatro venezolano": "委內瑞拉夸特羅琴",
    "Cavaquinho": "卡瓦基紐琴",
    "Tres": "三弦古巴吉他",
    "Tres cubano": "古巴三弦琴",
    "Requinto jarocho": "雷金托哈羅喬琴",
    "Jarana jarocha": "哈拉納哈羅喬琴",
    "Jarana": "哈拉納琴",
    "Vihuela mexicana": "維維拉琴",
    "Tiple colombiano": "哥倫比亞蒂普勒琴",
    "Ronroco": "朗羅科琴",
    "Cobza": "科布扎琴",
    "Laouto": "拉烏托琴",
    "Bouzouki": "布祖基琴",
    "Irish bouzouki": "愛爾蘭布祖基琴",
    "Tzouras": "特佐拉斯琴",
    "Baglamas": "巴格拉馬斯小琴",
    "Baglama": "巴格拉馬琴",
    "Saz": "薩茲琴",
    "Tanbur": "坦布爾琴",
    "Cumbus": "居姆布什琴",
    "Lavta": "拉夫塔琴",
    "Oud": "烏德琴",
    "Barbat": "巴爾巴特琴",
    "Tar": "塔爾琴",
    "Setar": "四弦琴",
    "Dotar": "多塔爾琴",
    "Dutar": "杜塔爾琴",
    "Rubab": "熱巴普",
    "Qanbus": "卡恩巴斯琴",
    "Kobza": "科布扎琴",
    "Bandura": "班杜拉琴",
    "Tsymbaly": "齊姆巴利琴",
    "Citole": "奇托勒琴",
    "Pandura": "潘杜拉琴",
    "Panduri": "潘杜里琴",
    "Cithara": "奇薩拉琴",
    "Lyre": "里拉琴",
    "Ancient Greek Lyre": "古希臘里拉琴",
    "Krar": "克拉爾琴",
    "Kissar": "基薩爾琴",
    "Begena": "貝格納琴",
    "Inanga": "伊南加琴",
    "Enanga": "恩南加琴",
    "Ennanga": "恩南加弓琴",
    "Nyatiti": "尼亞提提琴",
    "Kundi": "孔迪琴",
    "Bolon": "博隆琴",
    "Ngoni": "恩貢尼琴",
    "Donso ngoni": "多索恩貢尼琴",
    "Kamale ngoni": "卡馬雷恩貢尼琴",
    "Kora": "科拉琴",
    "Mvet": "姆維特琴",
    "Seperewa": "塞佩雷瓦琴",
    "Onavillu": "奧納維魯琴",
    "Yazh": "亞茲琴",
    "Rudra veena": "魯德拉維納琴",
    "Saraswati veena": "薩拉斯瓦蒂維納琴",
    "Chitra veena": "奇特拉維納琴",
    "Veena": "維納琴",
    "Gottuvadyam": "葛圖瓦賈姆琴",
    "Sitar": "西塔琴",
    "Sarod": "薩羅德琴",
    "Surbahar": "蘇爾巴哈琴",
    "Dilruba": "迪爾魯巴琴",
    "Esraj": "以斯拉吉琴",
    "Tanpura": "坦布拉琴",
    "Swarmandal": "斯瓦爾曼達爾琴",
    "Bulbul tarang": "布爾布爾塔朗琴",
    "Sansi": "桑西琴",
    "Ektara": "一弦琴",
    "Tumbi": "通比琴",
    "Dotar": "多塔爾琴",
    "Dutar": "杜塔爾琴",
    "Qobyz": "庫布茲琴",
    "Komuz": "庫姆茲琴",
    "Topshur": "托普舒爾琴",
    "Dombra": "冬不拉琴",
    "Yatga": "雅托格琴",
    "Gayageum": "伽倻琴",
    "Santur": "桑圖爾琴",
    "Santoor": "桑圖爾琴",
    "Hammered dulcimer": "揚琴",
    "Dulcimer": "達爾西默琴",
    "Appalachian dulcimer": "阿帕拉契達爾西默琴",
    "Mountain dulcimer": "山地達爾西默琴",
    "Psaltery": "薩泰里琴",
    "Bowed psaltery": "拉弦薩泰里琴",
    "Kacapi": "卡恰比琴",
    "Siter": "西特爾琴",
    "Celempung": "切倫蓬琴",
    "Koto": "箏",
    "Biwa": "琵琶（日本）",
    "Shamisen": "三味線",
    "Sanshin": "三線",
    "Taishogoto": "大正琴",
    "Taish goto": "大正琴",
    "Kokle": "科克勒琴",
    "Kankles": "坎克萊斯琴",
    "Gusli": "古斯里琴",
    "Psalmodikon": "薩爾莫迪康琴",
    "Psalmodicon": "薩爾莫迪康琴",
    "Zither": "齊特琴",
    "Hackbrett": "哈克布雷特琴",
    "Scheitholt": "沙特霍爾特琴",
    "Citera": "奇特拉琴",
    "Langeleik": "朗格萊克琴",
    "Hardingfele": "哈丹格爾小提琴",
    "Hummel": "胡梅爾琴",
    "Talharpa": "塔爾哈帕琴",
    "Tagelharpa": "塔格爾哈帕琴",
    "Jouhikko": "約伊希科琴",
    "Morin khuur": "馬頭琴",
    "Tsuur": "楚爾笛",
    "Valiha": "瓦利哈筒琴",
    "Malagasy tube zither": "馬達加斯加管形齊特琴",
    "Trough zither": "槽形齊特琴",
    "Tube zither": "管形齊特琴",
    "Bar zither": "棒形齊特琴",
    "Raft zither": "排形齊特琴",
    "Ground zither": "地面齊特琴",
    "Frame zither": "框架齊特琴",
    "Waldzither": "森林齊特琴",
    "Cittern": "希特恩琴",
    "Chapman stick": "查普曼觸弦琴",
    "Warr guitar": "瓦爾吉他",
    # 豎琴族
    "Harp": "豎琴",
    "Pedal harp": "踏板豎琴",
    "Lever harp": "拉桿豎琴",
    "Celtic harp": "凱爾特豎琴",
    "Concert harp": "音樂廳豎琴",
    "Welsh triple harp": "威爾斯三排豎琴",
    "Cross-strung harp": "交叉弦豎琴",
    "Inline chromatic harp": "直列半音豎琴",
    "Electric harp": "電豎琴",
    "Earth harp": "大地豎琴",
    "Space harp": "太空豎琴",
    "Laser harp": "雷射豎琴",
    "Glass harp": "玻璃豎琴",
    "Harp guitar": "豎琴吉他",
    "Harp lute": "豎琴魯特琴",
    "Aeolian harp": "風鳴豎琴",
    "Wankara lyre": "萬卡拉里拉琴",
    "Saung gauk": "緬甸豎琴",
    "Burmese saung": "緬甸豎琴",
    "Adungu": "阿杜古弓形豎琴",
    "African bow harp": "非洲弓形豎琴",
    "Kundi": "孔迪弓形豎琴",
    "Bolon": "博隆豎琴",
    "Ardin": "阿爾丁豎琴",
    "Litungu": "利通古琴",
    "Obokano": "奧博卡諾琴",
    "Nyatiti": "尼亞提提琴",
    "Enanga": "恩南加豎琴",
    "Simsimiyya": "西姆西米亞琴",
    "Bow harp": "弓形豎琴",
    "Ground bow": "地面弓",
    # 鍵盤樂器
    "Piano": "鋼琴",
    "Harpsichord": "大鍵琴",
    "Clavichord": "古鍵琴",
    "Organ": "管風琴",
    "Pipe organ": "管風琴",
    "Reed organ": "簧風琴",
    "Harmonium": "哈莫尼烏姆風琴",
    "Melodeon": "梅洛迪恩風琴",
    "Celesta": "鋼片琴",
    "Fortepiano": "早期鋼琴",
    "Prepared piano": "加工鋼琴",
    "Toy piano": "玩具鋼琴",
    "Clavinet": "電鋼琴",
    "Rhodes": "羅茲電鋼琴",
    "Wurlitzer": "武利澤電鋼琴",
    "Hammond organ": "哈蒙德電風琴",
    "Electric organ": "電風琴",
    "Clavioline": "克拉維奧林電鍵琴",
    "Ondioline": "昂迪奧林電子琴",
    "Novachord": "諾瓦科德電風琴",
    "Ondes Martenot": "馬特諾電子波琴",
    "Theremin": "特雷門琴",
    "Trautonium": "特勞托尼琴",
    "Telharmonium": "泰爾哈莫尼琴",
    "Stylophone": "風格電子筆琴",
    "Omnichord": "全音弦琴",
    "Optigan": "光學風琴",
    "Accordion": "手風琴",
    "Concertina": "六角手風琴",
    "Bandoneon": "班東尼琴",
    "Harmonica": "口琴",
    "Melodica": "口風琴",
    "Shruti box": "薩如提盒風琴",
    "Sheng": "笙",
    "Saenghwang": "笙簧（韓國）",
    "Khaen": "笙（寮國）",
    "Sho": "笙（日本）",
    "Hulusi": "葫蘆絲",
    "Bawu": "巴烏",
    # 打擊樂器
    "Marimba": "馬林巴琴",
    "Xylophone": "木琴",
    "Vibraphone": "顫音琴",
    "Glockenspiel": "鐘琴",
    "Tubular bell": "管鐘",
    "Carillon": "排鐘",
    "Handbell": "手搖鈴",
    "Handbells": "手搖鈴",
    "Crotales": "古代鈸",
    "Singing bowl": "頌缽",
    "Tingsha": "銅鈴",
    "Angklung": "安克隆竹琴",
    "Gamelan": "甘美蘭",
    "Gamelan degung": "巽他甘美蘭",
    "Balafon": "巴拉風木琴",
    "Gyil": "吉爾木琴",
    "Bianzhong": "編鐘",
    "Fangxiang": "方響",
    "Bonang": "邦昂鑼",
    "Saron": "薩隆",
    "Gong": "鑼",
    "Tam-tam": "大鑼",
    "Hang gong": "漢戈鑼",
    "Kkwaenggwari": "小鑼（韓國）",
    "Jing": "京鑼",
    "Agogo": "阿果果雙鈴",
    "Cowbell": "牛鈴",
    "Ghungroo": "腳鈴",
    "Ankle bells": "腳踝鈴",
    "Jingle bells": "鈴鐺",
    "Sleigh bells": "雪橇鈴",
    "Finger cymbals": "指鈸",
    "Clash cymbals": "對鈸",
    "Hi-hat": "踩鈸",
    "Splash cymbal": "濺鈸",
    "Suspended cymbal": "懸吊鈸",
    "Crotales": "古代鈸",
    "Castanets": "卡斯塔涅特板",
    "Clapper": "響板",
    "Spoons": "湯匙樂器",
    "Bones": "骨頭響板",
    "Slapstick": "啪啪板",
    "Whipcracking": "鞭聲",
    "Wood blocks": "木魚",
    "Temple blocks": "廟塊",
    "Woodblock": "木魚",
    "Mokugyo": "木魚（日本）",
    "Hyoshigi": "拍子木",
    "Log drum": "木槽鼓",
    "Slit drum": "裂縫鼓",
    "Taiko": "太鼓",
    "Nagado daiko": "長胴太鼓",
    "Shime daiko": "締太鼓",
    "Tsuzumi": "鼓（日本）",
    "Janggu": "杖鼓",
    "Changgu": "長鼓",
    "Drum kit": "爵士鼓",
    "Electronic drums": "電子鼓",
    "Djembe": "金貝鼓",
    "Dundun": "敦敦鼓",
    "Talking drum": "聲語鼓",
    "Tama": "塔馬鼓",
    "Kalangu": "卡朗古鼓",
    "Darbuka": "達布卡鼓",
    "Doumbek": "多姆貝克鼓",
    "Bendir": "本迪爾框鼓",
    "Dayereh": "達葉雷框鼓",
    "Mazhar": "馬扎爾框鼓",
    "Riq": "里格框鼓",
    "Daf": "達夫框鼓",
    "Pandeiro": "潘德羅框鼓",
    "Tamborim": "塔博林鼓",
    "Surdo": "蘇爾多鼓",
    "Repinique": "雷皮尼克鼓",
    "Caixa": "卡伊沙小鼓",
    "Zabumba": "扎布巴鼓",
    "Bombo legüero": "邦博鼓",
    "Davul": "達烏爾鼓",
    "Tapan": "塔潘鼓",
    "Dhol": "卓爾鼓",
    "Dholak": "卓拉克鼓",
    "Pakhawaj": "帕卡瓦吉鼓",
    "Mridangam": "姆里丹加鼓",
    "Tabla": "塔布拉鼓",
    "Tabla dayan": "塔布拉右鼓",
    "Tabla bayan": "塔布拉左鼓",
    "Kanjira": "坎吉拉鼓",
    "Ghatam": "甘塔姆陶鼓",
    "Udu": "烏杜陶鼓",
    "Madal": "馬達爾鼓",
    "Khol": "科爾鼓",
    "Mrdanga": "姆爾丹加鼓",
    "Nagado-daiko": "長胴太鼓",
    "Kendang": "肯當鼓",
    "Ashiko": "阿希科錐形鼓",
    "Bougarabou": "布加拉布鼓",
    "Conga": "康加鼓",
    "Bongo": "邦戈鼓",
    "Timbales": "蒂姆巴雷斯鼓",
    "Timbal": "蒂姆巴爾鼓",
    "Atabaque": "阿塔巴克鼓",
    "Nagara": "納加拉鼓",
    "Naqara": "納卡拉鼓",
    "Naqareh": "納卡雷鼓",
    "Nagada": "納加達鼓",
    "Naker": "納克爾鼓",
    "Powwow drum": "原住民集會鼓",
    "Ocean drum": "海浪鼓",
    "Rain drum": "雨聲鼓",
    "Handpan": "手碟",
    "Pantam": "潘塔姆手碟",
    "Rav vast": "拉夫瓦斯特手碟",
    "Steel tongue drum": "鋼舌鼓",
    "Hank drum": "漢克鼓",
    "Steel drum": "鋼鼓",
    "Steelpan": "鋼鍋琴",
    "Tank drum": "鋼舌鼓",
    "Reco-reco": "雷科雷科刮奏板",
    "Cabasa": "卡巴薩搖響器",
    "Maracas": "沙鈴",
    "Egg shaker": "蛋形沙鈴",
    "Asalato": "阿薩拉托搖響器",
    "Kashaka": "卡沙卡搖響器",
    "Shekere": "謝科雷搖響器",
    "Caxixi": "卡西西搖響器",
    "Chajchas": "查查斯蹄鈴",
    "Vibraslap": "顫音搖響器",
    "Guiro": "葫蘆刮奏器",
    "Frog guiro": "青蛙刮奏器",
    "Jawbone": "顎骨刮奏器",
    "Lithophone": "石琴",
    "Stone chimes": "石磬",
    "Slit gong": "縫鑼",
    "Bell": "鈴",
    "Tubular bell": "管鐘",
    "Tubular drum": "管狀鼓",
    "Pellet drum": "圓珠鼓",
    "Hourglass drum": "沙漏鼓",
    "Frame drum": "框架鼓",
    "Conical drum": "錐形鼓",
    "Cylindrical drum": "圓柱鼓",
    "Barrel drum": "桶鼓",
    "Friction drum": "摩擦鼓",
    "Rattle drum": "搖鼓",
    "Slit drum": "裂縫鼓",
    "Octoban": "八音桶鼓",
    "Ceramic percussion": "陶瓷打擊樂器",
    "Superball": "超彈球摩擦樂器",
    # 管樂（民族/世界）
    "Bansuri": "班蘇里笛",
    "Dizi": "笛子",
    "Xiao": "簫",
    "Paixiao": "排簫",
    "Guanzi": "管子",
    "Suona": "嗩吶",
    "Xun": "塤",
    "Hocchiku": "法竹尺八",
    "Shakuhachi": "尺八",
    "Hichiriki": "篳篥",
    "Piri": "觱篥",
    "Ney": "奈伊笛",
    "Kawala": "卡瓦拉笛",
    "Kaval": "卡瓦爾笛",
    "Duduk": "都杜克管",
    "Duduk bass": "低音都杜克管",
    "Balaban": "巴拉班管",
    "Mey": "梅依管",
    "Mijwiz": "米日維茲雙管笛",
    "Arghul": "阿爾胡爾雙管笛",
    "Launeddas": "勞內達斯三管笛",
    "Diple": "迪普勒雙管笛",
    "Gaita": "蓋塔笛/風笛",
    "Alboka": "阿爾博卡雙管笛",
    "Sipsi": "希普西笛",
    "Sralai": "斯拉萊管",
    "Khlui": "克盧伊笛",
    "Khloy": "克洛伊笛",
    "Pi nai": "披奈雙簧管",
    "Pi chanai": "披昌奈雙簧管",
    "Shehnai": "謝海笛",
    "Sorna": "索爾納嗩吶",
    "Zurna": "佐爾納嗩吶",
    "Mizmar": "米茲瑪爾嗩吶",
    "Pungi": "蛇笛",
    "Hulusi": "葫蘆絲",
    "Bawu": "巴烏",
    "Danso": "短簫（韓國）",
    "Quena": "克納笛",
    "Quenacho": "低音克納笛",
    "Siku": "西庫排笛",
    "Antara": "安塔拉排笛",
    "Pinkillu": "平基優笛",
    "Tarka": "塔爾卡笛",
    "Fujara": "富亞拉大笛",
    "Koncovka": "孔琴科夫卡笛",
    "Tilinca": "提林卡笛",
    "Tilink": "提林科笛",
    "Suling": "蘇靈笛",
    "Suling sunda": "巽他蘇靈笛",
    "Palendag": "帕倫達格笛",
    "Tumpong": "通蓬笛",
    "Phin pia": "品琵笛",
    "Pulalu": "普拉盧笛",
    "Buhay": "布哈伊竹笛",
    "Ney": "奈伊笛",
    "Nai": "奈依笛",
    "Flute": "長笛",
    "Fife": "六孔橫笛",
    "Piccolo": "短笛",
    "Pan flute": "排笛",
    "Pan pipes": "排笛",
    "Nose flute": "鼻笛",
    "Nose whistle": "鼻哨",
    "Hawaiian nose flute": "夏威夷鼻笛",
    "Willow flute": "柳笛",
    "Vessel flute": "球形笛",
    "Irish flute": "愛爾蘭橫笛",
    "Western flute": "西洋長笛",
    "Pitch pipe": "定音管",
    "Tabor pipe": "塔博管笛",
    "Gemshorn": "寶石角笛",
    "Txistu": "巴斯克笛",
    "Chalumeau": "夏呂莫單簧管",
    "Clarinet": "單簧管",
    "Basset horn": "巴色特管",
    "Bass clarinet": "低音單簧管",
    "Oboe": "雙簧管",
    "Cor anglais": "英國管",
    "English horn": "英國管",
    "Baritone oboe": "中低音雙簧管",
    "Oboe da caccia": "狩獵雙簧管",
    "Oboe d'amore": "愛之雙簧管",
    "Piccolo oboe": "高音雙簧管",
    "Bassoon": "低音管",
    "Contrabassoon": "倍低音管",
    "Tenoroon": "次中音低音管",
    "Heckelphone": "赫克爾低音雙簧管",
    "Saxophone": "薩克斯風",
    "C melody saxophone": "C調薩克斯風",
    "Sarrusophone": "薩魯梭風",
    "Bagpipe": "風笛",
    "Great highland bagpipe": "高地風笛",
    "Uilleann pipes": "愛爾蘭風笛",
    "Northumbrian smallpipes": "諾森伯蘭小風笛",
    "Gaida": "蓋達風笛",
    "Tulum": "圖盧姆風笛",
    "Zampogna": "扎姆波尼亞風笛",
    "Musette": "穆塞特小風笛",
    "Cornemuse du centre": "中部法國風笛",
    "Duda": "都達風笛",
    "Bombarde": "布雷塔尼轟炸管",
    "Shawm": "肖姆管",
    "Rauschpfeife": "勞施普費夫管",
    "Cromorne": "克洛莫恩管",
    "Cornamuse": "科爾納穆斯管",
    "Crumhorn": "彎管號",
    "Rackett": "拉克特管",
    "Curtall": "科塔爾管",
    "Dulcian": "達爾西安管",
    "Hirtenschalmei": "牧童肖姆管",
    "Pungi": "蛇笛",
    "Tarogato": "塔羅格陶管",
    "Sorna": "索爾納嗩吶",
    "Shehnai": "謝海笛",
    "Mizmar": "米茲瑪爾管",
    "Trumpets": "小號",
    "Trumpet": "小號",
    "Natural trumpet": "天然小號",
    "Chromatic trumpet": "半音小號",
    "Keyed bugle": "鍵式號",
    "Flugelhorn": "翼號",
    "Cornet": "短號",
    "Mellophone": "次中音號",
    "French horn": "法國號",
    "Wagner tuba": "瓦格納大號",
    "Trombone": "長號",
    "Sackbut": "薩克布特長號",
    "Euphonium": "上低音號",
    "Baritone horn": "中低音號",
    "Tuba": "大號",
    "Sousaphone": "低音大號",
    "Ophicleide": "奧菲克萊德號",
    "Serpent": "蛇形管號",
    "Didgeridoo": "迪吉里杜管",
    "Shofar": "羊角號",
    "Kudu horn": "犀牛角號",
    "Conch shell": "海螺",
    "Shankha": "印度海螺",
    "Pututu": "普圖圖海螺",
    "Olifant": "象牙號",
    "Dungchen": "藏傳長號",
    "Kangling": "脛骨號",
    "Lur": "盧爾號",
    "Carnyx": "卡爾尼克斯號",
    "Bucium": "布奇烏姆號",
    "Trembita": "特倫比塔長號",
    "Erke": "埃爾克角號",
    "Animal horn": "動物角號",
    "Pungi": "蛇笛",
    "Nagado daiko": "長胴太鼓",
    # 電子/當代
    "Synthesizer": "合成器",
    "Sampler": "取樣器",
    "Drum machine": "鼓機",
    "Mellotron": "梅樂頓",
    "Fairlight CMI": "費爾萊特CMI",
    "Synclavier": "辛克拉維耶取樣合成器",
    "EMS Synthi AKS": "EMS合成器",
    "Buchla synthesizer": "布克拉合成器",
    "Modular synth": "模組化合成器",
    "Granular synth": "顆粒合成器",
    "Groovebox": "節拍合成器",
    "Loop station": "循環錄音機",
    "Sequencer": "音序器",
    "MIDI controller": "MIDI控制器",
    "MPE controller": "MPE控制器",
    "Field recorder": "野外錄音機",
    "Tape machine": "磁帶機",
    "Akai MPC": "Akai MPC取樣機",
    "Stylophone": "電子筆琴",
    "Omnichord": "全音弦琴",
    "Optigan": "光學風琴",
    "Ondes Martenot": "馬特諾電子波琴",
    "Trautonium": "特勞托尼琴",
    "Theremin": "特雷門琴",
    "Clavioline": "克拉維奧林電子琴",
    "Ondioline": "昂迪奧林電子琴",
    "Novachord": "諾瓦科德電子琴",
    "Telharmonium": "泰爾哈莫尼電子琴",
    # 東南亞
    "Gamelan": "甘美蘭",
    "Angklung": "安克隆竹琴",
    "Kendang": "肯當鼓",
    "Suling": "蘇靈笛",
    "Kolintang": "科林塘",
    "Kulintang": "庫林塘",
    "Saron": "薩隆",
    "Reyong": "雷楊",
    "Ugal": "烏加爾",
    "Gender": "根德爾",
    "Gangsa": "剛薩",
    "Jegog": "傑格竹琴",
    "Luntang": "隆塘",
    "Kolintang": "科林塘",
    "Gandingan": "甘丁甘",
    "Tagutok": "塔古托克",
    "Kubing": "庫賓竹口琴",
    "Babendil": "巴本迪爾",
    "Kulintang a kayo": "木製庫林塘",
    "Kulintang a putao": "高音庫林塘",
    "Kulintang a tiniok": "低音庫林塘",
    "Kwintangan kayo": "昆坦甘木琴",
    "Dabakan": "達巴肯鼓",
    "Gandingan a kayo": "木製甘丁甘",
    "Kroncong": "科倫謅吉他",
    "Kacapi": "卡恰比琴",
    "Celempung": "切倫蓬琴",
    "Siter": "西特爾",
    "Ruan": "阮",
    "Phin pia": "品琵",
    "Saw duang": "素彈二弦琴",
    "Saw sam sai": "素三弦琴",
    "Saw u": "素烏二胡",
    "Khim": "克因揚琴",
    "Khim wong": "克因翁圓形琴",
    "Ranat ek": "木琴（泰國）",
    "Ranat thum": "低音泰國木琴",
    "Ranat ek lek": "鐵片泰國木琴",
    "Ranat thum lek": "低音鐵片泰國木琴",
    "Kong vong": "圓排鑼",
    "Roneat": "羅乃木琴",
    "Roneat ek": "高音羅乃木琴",
    "Roneat dek": "鐵片羅乃琴",
    "Pinpeat": "品批合奏",
    "Piphat": "皮帕合奏",
    "Khlui": "克盧伊笛",
    "Pi nai": "披奈管",
    "Pi chanai": "披昌奈管",
    "Phin pia": "品琵",
    "Pong lang": "蓬朗木琴",
    "Divan saz": "德萬薩茲",
    "Sralai": "斯拉萊管",
    "Janggu": "杖鼓",
    # 非洲
    "Kalimba": "卡林巴",
    "Mbira": "姆比拉",
    "Mbira nyunga nyunga": "尼揚加姆比拉",
    "Kalimba": "卡林巴",
    "Karimba": "卡林巴（辛巴威）",
    "Sansula": "桑蘇拉",
    "Sanza": "桑薩",
    "Ikembe": "伊肯貝",
    "Likembe": "利肯貝",
    "Array mbira": "陣列姆比拉",
    "Kisanji": "基桑吉",
    "Malimbe": "馬林貝",
    "Nyonganyonga": "尼揚加尼揚加琴",
    "Kundi": "孔迪豎琴",
    "Donso ngoni": "多索恩貢尼獵人琴",
    "Kamale ngoni": "卡馬雷恩貢尼",
    "Ngoni": "恩貢尼",
    "Kora": "科拉琴",
    "Mvet": "姆維特琴",
    "Seperewa": "塞佩雷瓦琴",
    "Gyil": "吉爾木琴",
    "Balafon": "巴拉風",
    "Amadinda": "阿馬丁達木琴",
    "Akadinda": "阿卡丁達木琴",
    "Kaffir piano": "南非鐵片琴",
    "Masenqo": "馬森科弓琴",
    "Begena": "貝格納豎琴",
    "Krar": "克拉爾里拉琴",
    "Kissar": "基薩爾里拉琴",
    "Inanga": "伊南加筒琴",
    "Enanga": "恩南加豎琴",
    "Ennanga": "恩南加弓豎琴",
    "Nyatiti": "尼亞提提八弦琴",
    "Umuduri": "烏姆杜里",
    "Agidigbo": "阿吉迪格博箱琴",
    "Adjalin": "阿賈林琴",
    "Djembe": "金貝鼓",
    "Dunun": "杜努恩鼓",
    "Dunun bass": "低音杜努恩鼓",
    "Tama": "塔馬變音鼓",
    "Talking drum": "聲語鼓",
    "Kalangu": "卡朗古鼓",
    "Bougarabou": "布加拉布鼓",
    "Ashiko": "阿希科錐形鼓",
    "Atabaque": "阿塔巴克鼓",
    "Shekere": "謝科雷葫蘆鈴",
    "Asalato": "阿薩拉托",
    "Kashaka": "卡沙卡連珠搖響器",
    "Lesiba": "萊西巴弓樂器",
    "Bobre": "博布雷弓樂器",
    "Musical bow": "音樂弓",
    "Gue": "格弓琴",
    "Onavillu": "奧納維魯弓琴",
    "Berimbau": "貝林包弓琴",
    "Umuduri": "烏姆杜里弓琴",
    "Simbi": "辛比琴",
    "Nyonganyonga": "尼揚加尼揚加",
    # 中東/波斯
    "Oud": "烏德琴",
    "Tar": "塔爾琴",
    "Setar": "四弦琴",
    "Dotar": "多塔爾琴",
    "Dutar": "杜塔爾琴",
    "Saz": "薩茲琴",
    "Tanbur": "坦布爾琴",
    "Tanbur turkish": "土耳其坦布爾琴",
    "Divan saz": "德萬薩茲琴",
    "Cumbus": "居姆布什琴",
    "Lavta": "拉夫塔琴",
    "Laouto": "拉烏托琴",
    "Santoor": "桑圖爾琴",
    "Santur": "桑圖爾琴",
    "Qanun": "卡農琴",
    "Kanun": "卡農琴",
    "Rebab": "熱巴普",
    "Ney": "奈伊笛",
    "Duduk": "都杜克管",
    "Balaban": "巴拉班管",
    "Mey": "梅依管",
    "Arghul": "阿爾胡爾雙管",
    "Mizmar": "米茲瑪爾",
    "Zurna": "佐爾納嗩吶",
    "Sorna": "索爾納嗩吶",
    "Zourna": "佐爾納",
    "Mijwiz": "米日維茲雙管",
    "Davul": "達烏爾鼓",
    "Riq": "里格手鼓",
    "Daf": "達夫框鼓",
    "Dayereh": "達葉雷框鼓",
    "Mazhar": "馬扎爾框鼓",
    "Bendir": "本迪爾框鼓",
    "Darbuka": "達布卡鼓",
    "Doumbek": "多姆貝克鼓",
    "Simsimiyya": "西姆西米亞竪琴",
    "Qanbus": "卡恩巴斯琴",
    "Takht": "塔赫特樂器",
    "Nay": "奈伊笛",
    "Kemenche": "克門切弓琴",
    "Classical kemenche": "古典克門切弓琴",
    "Karadeniz kemenche": "黑海克門切弓琴",
    # 中亞
    "Komuz": "庫姆茲琴",
    "Topshur": "托普舒爾琴",
    "Yatga": "雅托格琴",
    "Qobyz": "庫布茲琴",
    "Dombra": "冬不拉琴",
    "Dombyra": "冬不拉琴",
    "Dutar": "杜塔爾琴",
    "Dotar": "多塔爾琴",
    "Dotar": "多塔爾琴",
    "Ghijak": "吉賈克琴",
    "Igil": "伊吉勒馬頭琴",
    "Khomus": "口弦琴（雅庫特）",
    "Temir komuz": "鐵口弦琴",
    # 歐洲民俗
    "Hardanger fiddle": "哈丹格爾小提琴",
    "Nyckelharpa": "鍵鈕弓琴",
    "Hurdy-gurdy": "輪擦提琴",
    "Bagpipe": "風笛",
    "Gaida": "蓋達風笛",
    "Tulum": "圖盧姆風笛",
    "Zampogna": "義大利風笛",
    "Musette": "穆塞特小風笛",
    "Great highland bagpipe": "高地風笛",
    "Uilleann pipes": "愛爾蘭風笛",
    "Northumbrian smallpipes": "諾森伯蘭小風笛",
    "Cornemuse du centre": "法國中部風笛",
    "Bombarde": "布列塔尼轟炸管",
    "Launeddas": "撒丁島三管笛",
    "Diple": "克羅埃西亞雙管笛",
    "Cipla": "賽普勒斯雙管笛",
    "Fujara": "斯洛伐克富亞拉笛",
    "Koncovka": "斯洛伐克竹笛",
    "Tilinca": "羅馬尼亞笛",
    "Gadulka": "保加利亞弓琴",
    "Lijerica": "克羅埃西亞弓琴",
    "Gusle": "巴爾幹弓琴",
    "Tamburica": "坦布里察琴",
    "Cobza": "科布扎魯特琴",
    "Bandura": "班杜拉琴",
    "Tsymbaly": "奇姆巴利琴",
    "Gusli": "古斯里撥弦琴",
    "Kantele": "坎特萊琴",
    "Jouhikko": "約伊希科弓琴",
    "Kokle": "科克勒琴",
    "Kankles": "坎克萊斯琴",
    "Cimbalom": "欽巴隆揚琴",
    "Langeleik": "朗格萊克琴",
    "Epinette des vosges": "孚日山地琴",
    "Cittern": "希特恩琴",
    "Hurdy-gurdy": "輪擦提琴",
    "Scheitholt": "沙特霍爾特琴",
    "Citera": "奇特拉琴",
    "Hummel": "胡梅爾琴",
    "Hackbrett": "哈克布雷特敲擊琴",
    "Psalmodikon": "薩爾莫迪康琴",
    "Tagelharpa": "塔格爾哈帕弓琴",
    "Talharpa": "塔爾哈帕弓琴",
    "Crwth": "克魯斯弓琴",
    "Fiddle": "民俗小提琴",
    "Vielle": "中世紀弓琴",
    "Rebec": "雷貝克弓琴",
    "Gudok": "古多克弓琴",
    # 日本
    "Koto": "箏",
    "Biwa": "琵琶（日本）",
    "Shamisen": "三味線",
    "Sanshin": "三線（沖繩）",
    "Shakuhachi": "尺八",
    "Hichiriki": "篳篥",
    "Sho": "笙（日本）",
    "Ryuteki": "龍笛",
    "Kokyu": "胡弓",
    "Taishogoto": "大正琴",
    "Taish goto": "大正琴",
    "Tsuzumi": "鼓（日本）",
    "Nagado-daiko": "長胴太鼓",
    "Shime-daiko": "締太鼓",
    "Mokugyo": "木魚（日本）",
    "Hyoshigi": "拍子木",
    "Suikinkutsu": "水琴窟",
    "Shishi-odoshi": "鹿威嚇竹管",
    "Mukkuri": "姆庫里口弦",
    # 韓國
    "Gayageum": "伽倻琴",
    "Haegeum": "奚琴",
    "Haegum": "奚琴",
    "Geomungo": "玄鶴琴",
    "Janggu": "杖鼓",
    "Buk": "圓鼓",
    "Kkwaenggwari": "小鑼（農樂）",
    "Piri": "觱篥",
    "Danso": "短簫",
    "Saenghwang": "笙簧",
    "Ajaeng": "牙箏",
    # 南美/拉丁
    "Charango": "恰朗戈琴",
    "Ronroco": "朗羅科琴",
    "Vihuela mexicana": "維維拉琴",
    "Guitarrón mexicano": "墨西哥大吉他",
    "Bajo sexto": "六組低音吉他",
    "Jarana jarocha": "哈拉納哈羅喬琴",
    "Requinto jarocho": "雷金托哈羅喬琴",
    "Cuatro venezolano": "委內瑞拉夸特羅琴",
    "Tres cubano": "古巴三弦吉他",
    "Tres": "三弦古巴吉他",
    "Timple": "加那利小吉他",
    "Timple canario": "加那利群島小吉他",
    "Tiple colombiano": "哥倫比亞蒂普勒琴",
    "Tiple": "蒂普勒琴",
    "Quena": "克納笛",
    "Siku": "西庫排笛",
    "Antara": "安塔拉排笛",
    "Pinkillu": "平基優笛",
    "Tarka": "塔爾卡笛",
    "Pututu": "普圖圖海螺號",
    "Berimbau": "貝林包弓琴",
    "Atabaque": "阿塔巴克鼓",
    "Pandeiro": "潘德羅框鼓",
    "Tamborim": "塔博林鼓",
    "Surdo": "蘇爾多低音鼓",
    "Repinique": "雷皮尼克鼓",
    "Caixa": "卡伊沙小鼓",
    "Zabumba": "扎布巴大鼓",
    "Bombo legüero": "邦博大鼓",
    "Cuíca": "庫伊卡摩擦鼓",
    "Reco-reco": "雷科雷科竹刮器",
    "Agogô": "阿果果雙鈴",
    "Maracas": "沙鈴",
    "Caxixi": "卡西西搖響器",
    "Pandeiro": "潘德羅框鼓",
    "Marimbula": "馬林布拉",
    "Salterio mexicano": "墨西哥薩泰里琴",
    "Tiple": "蒂普勒",
    "Cuatro": "夸特羅",
    # 其他民族
    "Fujara": "富亞拉大笛",
    "Fujara bass": "低音富亞拉笛",
    "Nyckelharpa": "鍵鈕弓琴",
    "Kemençe": "克門切弓琴",
    "Pochette": "袋形小提琴",
    "Vielle": "維埃爾弓琴",
    "Didgeridoo": "迪吉里杜管",
    "Bullroarer": "牛吼板",
    "Bullroarer (music)": "牛吼板",
    "Wobble board": "搖板",
    "Lagerphone": "拉格電話搖響器",
    "Gumleaf": "桉樹葉笛",
    "Washtub bass": "洗衣盆貝斯",
    "Washboard": "洗衣板打擊樂器",
    "Jug": "陶壺樂器",
    "Mouth harp": "口弦琴",
    "Jaw harp": "口弦琴",
    "Jews harp": "口弦琴",
    "Kouxian": "口弦（中國）",
    "Morsing": "莫爾辛口弦琴",
    "Khomus": "克和木斯口弦琴",
    "Temir komuz": "鐵口弦琴",
    "Mukkuri": "姆庫里口弦",
    "Gogona": "果果納口弦",
    "Morchang": "莫爾強口弦琴",
    "Kubyz": "庫比茲口弦",
    "Guqin": "古琴",
    "Guzheng": "古箏",
    "Duxianqin": "獨弦琴",
    "Leiqin": "擂琴",
    "Liuqin": "柳琴",
    "Ruan": "阮",
    "Yueqin": "月琴",
    "Yangqin": "揚琴",
    "Banhu": "板胡",
    "Gaohu": "高胡",
    "Zhonghu": "中胡",
    "Jinghu": "京胡",
    "Tiqin": "提琴（廣東）",
    "Erxian": "二弦琴",
    "Erhu": "二胡",
    "Sihu": "四胡",
    "Pipa": "琵琶",
    "Dizi": "笛子",
    "Xiao": "簫",
    "Paixiao": "排簫",
    "Xun": "塤",
    "Guanzi": "管子",
    "Suona": "嗩吶",
    "Sheng": "笙",
    "Bianzhong": "編鐘",
    "Fangxiang": "方響",
    "Bawu": "巴烏",
    "Hulusi": "葫蘆絲",
    "Lithophone of vietnam": "越南石琴",
    "Dan bau": "獨弦琴（越南）",
    "Dan tranh": "箏（越南）",
    "Dan ty ba": "琵琶（越南）",
    "Dan moi": "口弦（越南）",
    "Dan tinh": "叮寧琴",
    "Ken bau": "越南笛",
    # 特殊樂器
    "Musical saw": "鋸子樂器",
    "Flexatone": "軟鋼片搖響器",
    "Glass harmonica": "玻璃琴",
    "Waterphone": "水音琴",
    "Cristal baschet": "水晶巴謝特琴",
    "Verrophone": "玻璃棒琴",
    "Glasschord": "玻璃鍵琴",
    "Hang": "手碟",
    "Handpan": "手碟",
    "Pantam": "潘塔姆手碟",
    "Rav vast": "拉夫瓦斯特手碟",
    "Steel tongue drum": "鋼舌鼓",
    "Hank drum": "漢克鋼舌鼓",
    "Kalimba": "卡林巴",
    "Tongue drum": "舌鼓",
    "Daxophone": "達索風音板",
    "Theremin": "特雷門琴",
    "Moodswinger": "情緒搖擺琴",
    "Long-string instrument": "長弦樂器",
    "Music on a long thin wire": "細線音樂",
    "Prepared piano": "加工鋼琴",
    "Toy piano": "玩具鋼琴",
    "Kaffir piano": "南非鐵片琴",
    "Thumb piano": "拇指琴",
    "Lap steel": "鋼棒滑音吉他",
    "Sasando": "薩桑多琴",
    "Valiha": "瓦利哈筒琴",
    "Malagasy tube zither": "馬達加斯加管形齊特琴",
    "Sasando": "薩桑多蘭葉琴",
    "Gordo": "高爾多大鼓",
    "Drum machine hybrid": "混合鼓機",
    "Drum machine": "鼓機",
    "Cymbal": "鈸",
}


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    data = {}
    for line in parts[1].splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            data[k.strip()] = v.strip().strip('"')
    return data, parts[2].strip()


def write_frontmatter(data, body, keep_fields):
    lines = []
    for field in keep_fields:
        if field in data:
            v = data[field]
            if any(c in v for c in ':"\\'):
                v = f'"{v}"'
            lines.append(f"{field}: {v}")
    fm = "\n".join(lines)
    return f"---\n{fm}\n---\n{body}\n"


KEEP_FIELDS = [
    "title", "original_name", "category", "country", "era",
    "sound_class", "hs_class", "family", "playing_method",
    "body_listening", "soundscape", "region_type",
]

KEEP_HEADINGS = {"## 介紹", "## 歷史背景", "## 音色描述", "### 讀者導覽"}


def process_file(path, dry_run=True):
    text = path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(text)
    if not meta:
        return False

    # 只保留指定標題行
    heading_lines = [l for l in body.splitlines() if l in KEEP_HEADINGS]
    new_body = "\n\n".join(heading_lines)

    title = meta.get("title", "")
    orig = meta.get("original_name", "")

    # 修正簡體→繁體
    for simp, trad in S2T_TITLE.items():
        if title == simp:
            title = trad

    # 修正混雜標題
    if title in MIXED_TITLE_FIX:
        title = MIXED_TITLE_FIX[title]

    # 英文標題→中文翻譯（用 original_name 查對照表）
    if orig and not any("一" <= c <= "鿿" for c in title):
        key = orig.strip("（暫譯）").strip()
        zh = EN_TO_ZH.get(key) or EN_TO_ZH.get(key.lower().title()) or EN_TO_ZH.get(key.title())
        if zh:
            title = zh

    meta["title"] = title
    new_text = write_frontmatter(meta, new_body, KEEP_FIELDS)
    if new_text != text:
        if not dry_run:
            path.write_text(new_text, encoding="utf-8")
        return True
    return False


def main():
    dry_run = "--apply" not in sys.argv
    if dry_run:
        print("=== DRY RUN ===")

    files = sorted(CONTENT_DIR.glob("*.md"))

    # 1. 刪除非樂器
    deleted = 0
    for path in files:
        if path.stem in NON_INSTRUMENT_SLUGS:
            if not dry_run:
                path.unlink()
                print(f"DELETED: {path.name}")
            else:
                print(f"[DELETE] {path.name}")
            deleted += 1

    # 2. 合併 steel-string-acoustic-guitar → acoustic-guitar
    merge_src = CONTENT_DIR / "steel-string-acoustic-guitar.md"
    if merge_src.exists() and merge_src.stem not in NON_INSTRUMENT_SLUGS:
        if not dry_run:
            merge_src.unlink()
            print("MERGED: steel-string-acoustic-guitar → acoustic-guitar")
        else:
            print("[MERGE] steel-string-acoustic-guitar → acoustic-guitar (刪除重複)")

    # 3. 修正剩餘檔案
    modified = 0
    for path in files:
        if path.stem in NON_INSTRUMENT_SLUGS:
            continue
        if path.stem == "steel-string-acoustic-guitar":
            continue
        changed = process_file(path, dry_run)
        if changed:
            modified += 1
            if dry_run:
                meta, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
                print(f"[MODIFY] {path.stem}: {meta.get('title')} → (updated)")

    print(f"\n{'DRY RUN' if dry_run else 'DONE'}: deleted={deleted}, modified={modified}")


if __name__ == "__main__":
    main()
